### ISSUE TITLE
Pull request into DXRando repo

### ISSUE THREAD

**Issue by Die4Ever** [hampta/deus-ex-randomizer-discord-bot#1]
This looks great, I think we should bring it into the main repo. Should probably make a new folder for it since it has multiple files. We can also make GitHub actions automatically build the exe file, I can help with that if you need.

**Comment by hampta** [comment]
I'll do a pull request a little later.

**Comment by hampta** [comment]
I'll do a pull request a little later.

**Comment by Die4Ever** [comment]
fixed here https://github.com/Die4Ever/deus-ex-randomizer/pull/395

thanks!
